### PR TITLE
Add initial .gitignore

### PR DESCRIPTION
**Pull request by sslavic**

### CODE REVIEW

**Comment by yjshen** [comment]
Please also add
```
*~
*#*#
*.#*
*.ipr
.metadata
lib/
```

**Comment by sslavic** [comment]
Updated PR with @yjshen suggestion.

**Comment by yjshen** [comment]
`*.ipr` for Intellij, `.metadata` for Eclipse and `lib/` for maven :)

**Comment by sslavic** [comment]
@yjshen better now?

**Comment by yjshen** [comment]
Looks good to me :)

**Comment by sijie** [comment]
this looks good to me. +1 thanks @sslavic and @yjshen

**Pull request merged**
